export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const REQUEST_EVENTS_SCHEDULE = "REQUEST_EVENTS_SCHEDULE";
export const REQUEST_EVENTS_SCHEDULE_SUCCESS = "REQUEST_EVENTS_SCHEDULE_SUCCESS";
export const REQUEST_EVENTS_SCHEDULE_FAILURE = "REQUEST_EVENTS_SCHEDULE_FAILURE";
